import { MlsBoard } from './types';

export const MLS_LIBRARY: MlsBoard[] = [
  {
    id: 'crmls',
    name: 'CRMLS',
    fullName: 'California Regional MLS',
    state: 'CA',
    region: 'Southern California',
    forms: [
      {
        id: 'crmls-rpa',
        formName: 'Residential Purchase Agreement',
        shortName: 'Purchase Agreement',
        version: 'Rev. 12/2024',
        pages: 6,
        requiredSignatures: 6,
        requiredInitials: 12,
        parties: ['buyer', 'seller', 'agent', 'broker'],
        conditionalTriggers: [
          {
            id: 'rpa-as-is',
            fieldLabel: 'As-Is sale selected',
            condition: 'Paragraph 11 "As-Is" checkbox is checked',
            requiresFormId: 'crmls-aia',
            requiresFormName: 'As-Is Addendum (AI)',
            note: 'As-Is sales require a separate Buyer Inspection Advisory and As-Is Addendum per C.A.R. guidelines.',
            enabled: true,
          },
          {
            id: 'rpa-hoa',
            fieldLabel: 'HOA / Common interest development',
            condition: 'Property is part of an HOA (checked in purchase agreement)',
            requiresFormId: 'crmls-hoa',
            requiresFormName: 'HOA Documents Addendum (HOAI)',
            note: 'HOA properties require disclosure of CC&Rs, financials, and meeting minutes per CA Civil Code §4525.',
            enabled: true,
          },
          {
            id: 'rpa-contingency',
            fieldLabel: 'Loan contingency active',
            condition: 'Loan contingency is not waived at time of compliance check',
            requiresFormId: 'crmls-lcr',
            requiresFormName: 'Loan Contingency Removal (CR)',
            note: 'Loan contingency must be formally removed before close. Failure to remove may void the contract.',
            enabled: true,
          },
        ],
      },
      {
        id: 'crmls-sda',
        formName: "Seller's Disclosure Addendum",
        shortName: "Seller's Disc.",
        version: 'Rev. 08/2023',
        pages: 8,
        requiredSignatures: 4,
        requiredInitials: 16,
        parties: ['seller', 'agent'],
        conditionalTriggers: [
          {
            id: 'sda-pool',
            fieldLabel: 'Pool / Spa present',
            condition: 'Seller answered Yes to pool or spa on disclosure',
            requiresFormId: 'crmls-spq',
            requiresFormName: 'Pool / Spa Disclosure (SPQ)',
            note: 'Properties with pools or spas require a separate Pool/Spa Questionnaire per CAR Form SPQ.',
            enabled: true,
          },
          {
            id: 'sda-pre1978',
            fieldLabel: 'Home built before 1978',
            condition: 'Property year built is prior to 1978',
            requiresFormId: 'crmls-lpd',
            requiresFormName: 'Lead-Based Paint Disclosure',
            note: 'Federal law (42 U.S.C. §4852d) requires lead paint disclosure for all pre-1978 housing.',
            enabled: true,
          },
          {
            id: 'sda-septic',
            fieldLabel: 'Septic / private sewage system',
            condition: 'Seller disclosed property uses septic system',
            requiresFormId: 'crmls-ssa',
            requiresFormName: 'Septic System Addendum (SEPTA)',
            note: 'Septic systems require inspection and addendum disclosing system location, age, and last service date.',
            enabled: true,
          },
          {
            id: 'sda-solar',
            fieldLabel: 'Solar panels — leased or PPA',
            condition: 'Seller disclosed solar panels are leased or under a power purchase agreement',
            requiresFormId: 'crmls-solar',
            requiresFormName: 'Solar Lease / PPA Addendum (SLPA)',
            note: 'Leased solar systems transfer with property. Buyer must acknowledge assumption of lease obligations.',
            enabled: true,
          },
          {
            id: 'sda-tenant',
            fieldLabel: 'Tenant in occupancy',
            condition: 'Property is currently tenant-occupied per disclosure',
            requiresFormId: 'crmls-tia',
            requiresFormName: 'Tenant Occupied Property Addendum (TOPA)',
            note: 'Tenant-occupied properties require disclosure of lease terms and tenant rights under CA law.',
            enabled: true,
          },
          {
            id: 'sda-well',
            fieldLabel: 'Private well on property',
            condition: 'Seller disclosed a private well as the water source',
            requiresFormId: 'crmls-wa',
            requiresFormName: 'Well Addendum (WA)',
            note: 'Private wells require water quality testing and addendum disclosing condition and test results.',
            enabled: false,
          },
        ],
      },
      {
        id: 'crmls-lpd',
        formName: 'Lead-Based Paint Disclosure',
        shortName: 'Lead Paint',
        version: 'Federal (2010)',
        pages: 2,
        requiredSignatures: 4,
        requiredInitials: 0,
        parties: ['buyer', 'seller', 'agent'],
      },
      {
        id: 'crmls-coa',
        formName: 'Counter Offer Addendum',
        shortName: 'Counter Offer',
        version: 'Rev. 04/2024',
        pages: 1,
        requiredSignatures: 3,
        requiredInitials: 0,
        parties: ['buyer', 'seller'],
      },
      {
        id: 'crmls-la',
        formName: 'Listing Agreement – Exclusive Right to Sell',
        shortName: 'Listing Agreement',
        version: 'Rev. 01/2025',
        pages: 5,
        requiredSignatures: 3,
        requiredInitials: 5,
        parties: ['seller', 'agent', 'broker'],
        conditionalTriggers: [
          {
            id: 'la-shortsale',
            fieldLabel: 'Short sale / lender approval required',
            condition: 'Listing agreement indicates sale subject to lender short sale approval',
            requiresFormId: 'crmls-ssa2',
            requiresFormName: 'Short Sale Addendum (SSA)',
            note: 'Short sales require lender approval addendum and disclosure of lender negotiation timeline.',
            enabled: true,
          },
          {
            id: 'la-exclusion',
            fieldLabel: 'Seller exclusion listed',
            condition: 'Listing agreement contains buyer exclusions',
            requiresFormId: 'crmls-sel',
            requiresFormName: 'Seller Exclusion Addendum',
            note: 'Named buyer exclusions must be documented in a separate addendum to protect agent commission.',
            enabled: true,
          },
        ],
      },
      {
        id: 'crmls-bpa',
        formName: "Buyer's Representation Agreement",
        shortName: "Buyer's Rep.",
        version: 'Rev. 08/2024',
        pages: 3,
        requiredSignatures: 2,
        requiredInitials: 4,
        parties: ['buyer', 'agent'],
        conditionalTriggers: [
          {
            id: 'bpa-comp',
            fieldLabel: 'Buyer compensation terms modified',
            condition: 'Non-standard compensation terms are specified in the buyer rep agreement',
            requiresFormId: 'crmls-bcm',
            requiresFormName: 'Buyer Compensation Modification',
            note: 'Modified compensation terms must be separately acknowledged per NAR settlement rules (Aug 2024).',
            enabled: true,
          },
        ],
      },
    ],
  },
  {
    id: 'har',
    name: 'HAR',
    fullName: 'Houston Association of Realtors',
    state: 'TX',
    region: 'Greater Houston',
    forms: [
      {
        id: 'har-orc',
        formName: 'One to Four Family Residential Contract',
        shortName: 'Residential Contract',
        version: 'TREC 20-17',
        pages: 9,
        requiredSignatures: 8,
        requiredInitials: 18,
        parties: ['buyer', 'seller', 'agent', 'broker'],
        conditionalTriggers: [
          {
            id: 'har-survey',
            fieldLabel: 'Survey required by buyer',
            condition: 'Paragraph 6C indicates buyer requires a new survey',
            requiresFormId: 'har-survey-add',
            requiresFormName: 'Survey Deletion / Amendment Addendum',
            note: 'If a new survey is required, the Survey Deletion Addendum must be attached if seller declines to provide.',
            enabled: true,
          },
          {
            id: 'har-hoa',
            fieldLabel: 'HOA fees / restrictions apply',
            condition: 'Property subject to mandatory HOA (checked in contract body)',
            requiresFormId: 'har-hoa-add',
            requiresFormName: 'Addendum for Property Subject to Mandatory HOA',
            note: 'TREC requires the mandatory HOA addendum when the property has a mandatory HOA.',
            enabled: true,
          },
          {
            id: 'har-septic',
            fieldLabel: 'On-site sewage facility (septic)',
            condition: 'Contract indicates property uses an OSSF / septic system',
            requiresFormId: 'har-ossf',
            requiresFormName: 'Addendum for OSSF (Septic)',
            note: 'Properties with on-site sewage facilities require the TREC OSSF Addendum.',
            enabled: true,
          },
        ],
      },
      {
        id: 'har-sd',
        formName: 'Sellers Disclosure Notice',
        shortName: "Seller's Disc.",
        version: 'TREC OP-H',
        pages: 6,
        requiredSignatures: 2,
        requiredInitials: 6,
        parties: ['seller'],
        conditionalTriggers: [
          {
            id: 'har-flood',
            fieldLabel: 'Property in flood zone / flooded before',
            condition: 'Seller answered Yes to prior flooding or flood zone disclosure',
            requiresFormId: 'har-flood-add',
            requiresFormName: 'Flood Disclosure Addendum',
            note: 'Texas law (SB 339) requires written flood disclosure for properties with prior flood damage.',
            enabled: true,
          },
        ],
      },
      {
        id: 'har-tala',
        formName: 'Texas Listing Agreement',
        shortName: 'Listing Agreement',
        version: 'TREC LS-15',
        pages: 4,
        requiredSignatures: 3,
        requiredInitials: 4,
        parties: ['seller', 'agent'],
      },
      {
        id: 'har-lpd',
        formName: 'Lead Paint Addendum',
        shortName: 'Lead Paint',
        version: 'Federal (2010)',
        pages: 1,
        requiredSignatures: 3,
        requiredInitials: 0,
        parties: ['buyer', 'seller', 'agent'],
      },
    ],
  },
  {
    id: 'nwmls',
    name: 'NWMLS',
    fullName: 'Northwest MLS',
    state: 'WA',
    region: 'Pacific Northwest',
    forms: [
      {
        id: 'nwmls-psa',
        formName: 'Purchase & Sale Agreement',
        shortName: 'Purchase & Sale',
        version: 'Form 21 (2025)',
        pages: 7,
        requiredSignatures: 6,
        requiredInitials: 14,
        parties: ['buyer', 'seller', 'agent'],
        conditionalTriggers: [
          {
            id: 'nwmls-inspection',
            fieldLabel: 'Inspection contingency retained',
            condition: 'Buyer did not waive inspection contingency',
            requiresFormId: 'nwmls-form35',
            requiresFormName: 'Inspection Contingency (Form 35)',
            note: 'If the inspection contingency is active, Form 35 must be attached and signed by both parties.',
            enabled: true,
          },
          {
            id: 'nwmls-septic',
            fieldLabel: 'On-site septic system',
            condition: 'Property uses a septic / on-site sewage system',
            requiresFormId: 'nwmls-form22s',
            requiresFormName: 'On-Site Sewage Addendum (Form 22S)',
            note: 'WA law requires Form 22S for properties with on-site sewage disposal systems.',
            enabled: true,
          },
        ],
      },
      {
        id: 'nwmls-sds',
        formName: 'Seller Disclosure Statement',
        shortName: "Seller's Disc.",
        version: 'Form 17 (2024)',
        pages: 5,
        requiredSignatures: 2,
        requiredInitials: 10,
        parties: ['seller'],
      },
      {
        id: 'nwmls-addendum',
        formName: 'Optional Clauses Addendum',
        shortName: 'Optional Clauses',
        version: 'Form 22D',
        pages: 2,
        requiredSignatures: 2,
        requiredInitials: 0,
        parties: ['buyer', 'seller'],
      },
    ],
  },
  {
    id: 'mred',
    name: 'MRED',
    fullName: 'Midwest Real Estate Data',
    state: 'IL',
    region: 'Chicagoland',
    forms: [
      {
        id: 'mred-rpa',
        formName: 'Multi-Board Residential Real Estate Contract',
        shortName: 'Purchase Contract',
        version: '7.0 (2024)',
        pages: 8,
        requiredSignatures: 8,
        requiredInitials: 16,
        parties: ['buyer', 'seller', 'agent', 'broker'],
        conditionalTriggers: [
          {
            id: 'mred-attorney',
            fieldLabel: 'Attorney approval period active',
            condition: 'Attorney approval period has not been waived or expired',
            requiresFormId: 'mred-ala',
            requiresFormName: 'Attorney Approval Addendum',
            note: 'IL contracts include a 5-business-day attorney approval period unless expressly waived.',
            enabled: true,
          },
          {
            id: 'mred-condo',
            fieldLabel: 'Condominium / co-op unit',
            condition: 'Property type is condominium or co-op',
            requiresFormId: 'mred-cd',
            requiresFormName: 'Condo / Co-op Disclosure Addendum',
            note: 'IL Condo Act requires disclosure of association budgets, assessments, and rules prior to contract.',
            enabled: true,
          },
        ],
      },
      {
        id: 'mred-sd',
        formName: 'Residential Real Property Disclosure Report',
        shortName: 'Disclosure Report',
        version: 'IL Statutory',
        pages: 3,
        requiredSignatures: 3,
        requiredInitials: 0,
        parties: ['seller', 'buyer'],
        conditionalTriggers: [
          {
            id: 'mred-radon',
            fieldLabel: 'Radon test performed or elevated levels',
            condition: 'Seller disclosed radon testing or elevated radon levels',
            requiresFormId: 'mred-radon-disc',
            requiresFormName: 'Radon Disclosure Addendum',
            note: 'IL Radon Awareness Act requires written radon disclosure and test results when applicable.',
            enabled: true,
          },
        ],
      },
      {
        id: 'mred-ala',
        formName: 'Attorney Approval Addendum',
        shortName: 'Attorney Approval',
        version: 'MRED 2023',
        pages: 1,
        requiredSignatures: 2,
        requiredInitials: 0,
        parties: ['buyer', 'seller'],
      },
    ],
  },
  {
    id: 'bright',
    name: 'Bright MLS',
    fullName: 'Bright Multiple Listing Service',
    state: 'MD/VA/DC',
    region: 'Mid-Atlantic',
    forms: [
      {
        id: 'bright-repc',
        formName: 'Regional Sales Contract',
        shortName: 'Sales Contract',
        version: 'MAR 2024',
        pages: 10,
        requiredSignatures: 8,
        requiredInitials: 20,
        parties: ['buyer', 'seller', 'agent', 'broker'],
        conditionalTriggers: [
          {
            id: 'bright-hoa',
            fieldLabel: 'HOA / condo association',
            condition: 'Property is subject to HOA or condo association',
            requiresFormId: 'bright-hoa-disc',
            requiresFormName: 'HOA / Condo Disclosure Addendum',
            note: 'MD law requires HOA disclosure packet be provided to buyer within 7 days of contract ratification.',
            enabled: true,
          },
          {
            id: 'bright-firstlook',
            fieldLabel: 'First Look program / owner-occupant preference',
            condition: 'Property listed under First Look or similar owner-occupant program',
            requiresFormId: 'bright-fl',
            requiresFormName: 'First Look / Owner-Occupant Addendum',
            note: 'HUD First Look and similar programs require an addendum confirming buyer occupancy intent.',
            enabled: false,
          },
        ],
      },
      {
        id: 'bright-sd',
        formName: 'Residential Property Disclosure/Disclaimer',
        shortName: "Seller's Disc.",
        version: 'MAR Form (2023)',
        pages: 4,
        requiredSignatures: 3,
        requiredInitials: 4,
        parties: ['seller', 'buyer'],
        conditionalTriggers: [
          {
            id: 'bright-pre1978',
            fieldLabel: 'Home built before 1978',
            condition: 'Property year built is prior to 1978',
            requiresFormId: 'bright-lpd',
            requiresFormName: 'Lead-Based Paint Disclosure',
            note: 'Federal law (42 U.S.C. §4852d) requires lead paint disclosure for all pre-1978 housing.',
            enabled: true,
          },
        ],
      },
    ],
  },
  {
    id: 'heartland-ks',
    name: 'Heartland MLS',
    fullName: 'Heartland Multiple Listing Service',
    state: 'KS',
    region: 'Kansas',
    forms: [
      {
        id: 'hmls-rpa-ks',
        formName: 'Residential Real Estate Contract',
        shortName: 'Purchase Contract',
        version: 'HMLS 2024',
        pages: 8,
        requiredSignatures: 6,
        requiredInitials: 10,
        parties: ['buyer', 'seller', 'agent', 'broker'],
        conditionalTriggers: [
          {
            id: 'hmls-ks-as-is',
            fieldLabel: 'As-Is sale selected',
            condition: 'As-Is checkbox is checked',
            requiresFormId: 'hmls-aia',
            requiresFormName: 'As-Is Addendum',
            note: 'As-Is sales require a signed As-Is Addendum per Heartland MLS guidelines.',
            enabled: true,
          },
          {
            id: 'hmls-ks-hoa',
            fieldLabel: 'HOA exists',
            condition: 'HOA/Association dues field is not empty',
            requiresFormId: 'hmls-hoa',
            requiresFormName: 'HOA Addendum',
            note: 'Properties with an HOA require the HOA Addendum disclosing dues, rules, and transfer fees.',
            enabled: true,
          },
          {
            id: 'hmls-ks-pre1978',
            fieldLabel: 'Home built before 1978',
            condition: 'Property year built is prior to 1978',
            requiresFormId: 'hmls-lpd',
            requiresFormName: 'Lead-Based Paint Disclosure',
            note: 'Federal law requires lead paint disclosure for all pre-1978 housing.',
            enabled: true,
          },
        ],
      },
      {
        id: 'hmls-sd-ks',
        formName: 'Residential Real Property Disclosure',
        shortName: "Seller's Disclosure",
        version: 'HMLS 2024',
        pages: 4,
        requiredSignatures: 3,
        requiredInitials: 4,
        parties: ['seller', 'buyer'],
        conditionalTriggers: [
          {
            id: 'hmls-ks-pool',
            fieldLabel: 'Pool / spa present',
            condition: 'Pool or spa checkbox is checked',
            requiresFormId: 'hmls-pool',
            requiresFormName: 'Pool / Spa Disclosure',
            note: 'Pool or spa on property requires a Pool/Spa Disclosure addendum.',
            enabled: true,
          },
          {
            id: 'hmls-ks-septic',
            fieldLabel: 'Septic system present',
            condition: 'Septic system checkbox is checked',
            requiresFormId: 'hmls-septic',
            requiresFormName: 'Septic / Well Addendum',
            note: 'Properties with septic or well systems require the Septic/Well Addendum.',
            enabled: true,
          },
        ],
      },
    ],
  },
  {
    id: 'heartland-mo',
    name: 'Heartland MLS',
    fullName: 'Heartland Multiple Listing Service',
    state: 'MO',
    region: 'Missouri',
    forms: [
      {
        id: 'hmls-rpa-mo',
        formName: 'Residential Real Estate Contract',
        shortName: 'Purchase Contract',
        version: 'HMLS 2024',
        pages: 8,
        requiredSignatures: 6,
        requiredInitials: 10,
        parties: ['buyer', 'seller', 'agent', 'broker'],
        conditionalTriggers: [
          {
            id: 'hmls-mo-as-is',
            fieldLabel: 'As-Is sale selected',
            condition: 'As-Is checkbox is checked',
            requiresFormId: 'hmls-aia',
            requiresFormName: 'As-Is Addendum',
            note: 'As-Is sales require a signed As-Is Addendum per Heartland MLS guidelines.',
            enabled: true,
          },
          {
            id: 'hmls-mo-hoa',
            fieldLabel: 'HOA exists',
            condition: 'HOA/Association dues field is not empty',
            requiresFormId: 'hmls-hoa',
            requiresFormName: 'HOA Addendum',
            note: 'Properties with an HOA require the HOA Addendum disclosing dues, rules, and transfer fees.',
            enabled: true,
          },
          {
            id: 'hmls-mo-pre1978',
            fieldLabel: 'Home built before 1978',
            condition: 'Property year built is prior to 1978',
            requiresFormId: 'hmls-lpd',
            requiresFormName: 'Lead-Based Paint Disclosure',
            note: 'Federal law requires lead paint disclosure for all pre-1978 housing.',
            enabled: true,
          },
        ],
      },
      {
        id: 'hmls-sd-mo',
        formName: 'Residential Real Property Disclosure',
        shortName: "Seller's Disclosure",
        version: 'HMLS 2024',
        pages: 4,
        requiredSignatures: 3,
        requiredInitials: 4,
        parties: ['seller', 'buyer'],
        conditionalTriggers: [
          {
            id: 'hmls-mo-pool',
            fieldLabel: 'Pool / spa present',
            condition: 'Pool or spa checkbox is checked',
            requiresFormId: 'hmls-pool',
            requiresFormName: 'Pool / Spa Disclosure',
            note: 'Pool or spa on property requires a Pool/Spa Disclosure addendum.',
            enabled: true,
          },
          {
            id: 'hmls-mo-septic',
            fieldLabel: 'Septic system present',
            condition: 'Septic system checkbox is checked',
            requiresFormId: 'hmls-septic',
            requiresFormName: 'Septic / Well Addendum',
            note: 'Properties with septic or well systems require the Septic/Well Addendum.',
            enabled: true,
          },
        ],
      },
    ],
  },
];
