import { PdfField } from '@/types'

export const SELLER_DISCLOSURE_FIELDS: PdfField[] = [
  { key: "seller_1_name", label: "Seller 1 Name / Marital Status", page: 1, type: "text", x: 0, y: 0, width: 260, fontSize: 11, section: "seller_property" },
  { key: "seller_2_name", label: "Seller 2 Name / Marital Status", page: 1, type: "text", x: 0, y: 0, width: 260, fontSize: 11, section: "seller_property" },
  { key: "property_address", label: "Property Address", page: 1, type: "text", x: 0, y: 0, width: 380, fontSize: 11, section: "seller_property" },
  { key: "property_age", label: "Approximate Age of Property", page: 1, type: "text", x: 0, y: 0, width: 60, fontSize: 11, section: "occupancy" },
  { key: "years_owned", label: "How Long Have You Owned Property", page: 1, type: "text", x: 0, y: 0, width: 60, fontSize: 11, section: "occupancy" },
  { key: "seller_occupies_property", label: "Seller Occupies Property", page: 1, type: "choice", choices: ["yes", "no"], x: 0, y: 0, section: "occupancy" },
  { key: "seller_last_occupied_interval", label: "If No, Last Occupied Interval", page: 1, type: "text", x: 0, y: 0, width: 120, fontSize: 11, section: "occupancy" },
  { key: "seller_never_occupied", label: "Seller Has Never Occupied", page: 1, type: "choice", choices: ["yes", "no"], x: 0, y: 0, section: "occupancy" },
  { key: "construction_type", label: "Construction Type", page: 1, type: "text", x: 0, y: 0, width: 140, fontSize: 11, section: "construction" },
  { key: "construction_type_other", label: "Construction Type Other", page: 1, type: "text", x: 0, y: 0, width: 140, fontSize: 11, section: "construction" },
  { key: "land_fill_or_expansive_soil", label: "Land - Fill or Expansive Soil", page: 1, type: "choice", choices: ["yes", "no"], x: 0, y: 0, section: "land" },
  { key: "land_sliding_or_settling", label: "Land - Sliding / Settling / Movement", page: 1, type: "choice", choices: ["yes", "no"], x: 0, y: 0, section: "land" },
  { key: "land_flood_zone", label: "Land - In Flood Zone", page: 1, type: "choice", choices: ["yes", "no"], x: 0, y: 0, section: "land" },
  { key: "land_drainage_or_flood_problems", label: "Land - Drainage / Flood Problems", page: 1, type: "choice", choices: ["yes", "no"], x: 0, y: 0, section: "land" },
  { key: "land_explanation", label: "Land Explanation", page: 2, type: "textarea", x: 0, y: 0, width: 460, height: 50, fontSize: 10, multiline: true, section: "land" },
  { key: "roof_age_years", label: "Roof Approximate Age (years)", page: 2, type: "text", x: 0, y: 0, width: 50, fontSize: 11, section: "roof" },
  { key: "roof_problems", label: "Roof Problems", page: 2, type: "choice", choices: ["yes", "no"], x: 0, y: 0, section: "roof" },
  { key: "roof_problem_date", label: "Roof Problem Date", page: 2, type: "date", x: 0, y: 0, width: 80, fontSize: 11, section: "roof" },
  { key: "roof_repair_date", label: "Roof Repair Date", page: 2, type: "date", x: 0, y: 0, width: 80, fontSize: 11, section: "roof" },
  { key: "roof_explanation", label: "Roof Explanation", page: 2, type: "textarea", x: 0, y: 0, width: 460, height: 46, fontSize: 10, multiline: true, section: "roof" },
  { key: "plumbing_explanation", label: "Plumbing Explanation", page: 3, type: "textarea", x: 0, y: 0, width: 460, height: 46, fontSize: 10, multiline: true, section: "plumbing" },
  { key: "hvac_has_air_conditioning", label: "Has Air Conditioning", page: 4, type: "choice", choices: ["yes", "no"], x: 0, y: 0, section: "hvac" },
  { key: "electrical_problem_explanation", label: "Electrical Problem Explanation", page: 4, type: "textarea", x: 0, y: 0, width: 460, height: 38, fontSize: 10, multiline: true, section: "electrical" },
  { key: "hoa_amount", label: "HOA Amount", page: 5, type: "text", x: 0, y: 0, width: 60, fontSize: 11, section: "tax_hoa" },
  { key: "hoa_explanation", label: "HOA Explanation", page: 5, type: "textarea", x: 0, y: 0, width: 460, height: 36, fontSize: 10, multiline: true, section: "tax_hoa" },
  { key: "utility_electric_name", label: "Electric Company Name", page: 6, type: "text", x: 0, y: 0, width: 180, fontSize: 11, section: "utilities" },
  { key: "electronics_systems_present", label: "Electronic Systems Present", page: 6, type: "choice", choices: ["na", "yes", "no"], x: 0, y: 0, section: "electronics" },
  { key: "fixtures_air_conditioning_central", label: "Central Air Conditioning", page: 7, type: "fixture_status", choices: ["OS", "EX", "NA", "NS"], x: 0, y: 0, section: "fixtures" },
  { key: "fixtures_heating_system", label: "Heating System", page: 7, type: "fixture_status", choices: ["OS", "EX", "NA", "NS"], x: 0, y: 0, section: "fixtures" },
  { key: "fixtures_water_heater", label: "Water Heater", page: 7, type: "fixture_status", choices: ["OS", "EX", "NA", "NS"], x: 0, y: 0, section: "fixtures" },
  { key: "fixtures_ceiling_fans", label: "Ceiling Fans", page: 7, type: "fixture_status", choices: ["OS", "EX", "NA", "NS"], x: 0, y: 0, section: "fixtures" },
  { key: "kitchen_stove_range", label: "Kitchen - Stove / Range", page: 8, type: "fixture_status", choices: ["OS", "EX", "NA", "NS"], x: 0, y: 0, section: "fixtures" },
  { key: "kitchen_refrigerator", label: "Kitchen - Refrigerator", page: 8, type: "fixture_status", choices: ["OS", "EX", "NA", "NS"], x: 0, y: 0, section: "fixtures" },
  { key: "kitchen_dishwasher", label: "Kitchen - Dishwasher", page: 8, type: "fixture_status", choices: ["OS", "EX", "NA", "NS"], x: 0, y: 0, section: "fixtures" },
  { key: "material_information_disclosure", label: "Material Information Disclosure", page: 8, type: "textarea", x: 0, y: 0, width: 470, height: 58, fontSize: 10, multiline: true, section: "final" },
  { key: "seller_1_signature", label: "Seller 1 Signature", page: 8, type: "signature", x: 0, y: 0, width: 180, section: "signatures" },
  { key: "seller_1_date", label: "Seller 1 Date", page: 8, type: "date", x: 0, y: 0, width: 80, fontSize: 11, section: "signatures" },
  { key: "seller_2_signature", label: "Seller 2 Signature", page: 8, type: "signature", x: 0, y: 0, width: 180, section: "signatures" },
  { key: "seller_2_date", label: "Seller 2 Date", page: 8, type: "date", x: 0, y: 0, width: 80, fontSize: 11, section: "signatures" },
  { key: "buyer_1_signature", label: "Buyer 1 Signature", page: 8, type: "signature", x: 0, y: 0, width: 180, section: "signatures" },
  { key: "buyer_1_date", label: "Buyer 1 Date", page: 8, type: "date", x: 0, y: 0, width: 80, fontSize: 11, section: "signatures" },
  { key: "buyer_2_signature", label: "Buyer 2 Signature", page: 8, type: "signature", x: 0, y: 0, width: 180, section: "signatures" },
  { key: "buyer_2_date", label: "Buyer 2 Date", page: 8, type: "date", x: 0, y: 0, width: 80, fontSize: 11, section: "signatures" },
]
