import { PdfField } from '@/types'

// ─── SELLER'S DISCLOSURE AND CONDITION OF PROPERTY ADDENDUM ──────────────────
// Full 8-page field registry. All coordinates start at (0,0) and are set
// via the visual mapper at /admin/mapper.
// ─────────────────────────────────────────────────────────────────────────────

export const SELLER_DISCLOSURE_FIELDS: PdfField[] = [

  // ── PAGE 1: HEADER & OCCUPANCY ─────────────────────────────────────────────
  { key: 'seller_1_name',           label: 'Seller 1 Name / Marital Status',          page: 1, type: 'text',    x: 0, y: 0, width: 300, fontSize: 10, section: 'header' },
  { key: 'seller_2_name',           label: 'Seller 2 Name / Marital Status',          page: 1, type: 'text',    x: 0, y: 0, width: 300, fontSize: 10, section: 'header' },
  { key: 'property_address',        label: 'Property Address',                         page: 1, type: 'text',    x: 0, y: 0, width: 380, fontSize: 10, section: 'header' },

  // Section 3 – Occupancy
  { key: 'occ_property_age',        label: 'Approximate Age of Property',              page: 1, type: 'text',    x: 0, y: 0, width: 60,  fontSize: 10, section: 'occupancy' },
  { key: 'occ_years_owned',         label: 'How Long Have You Owned',                  page: 1, type: 'text',    x: 0, y: 0, width: 60,  fontSize: 10, section: 'occupancy' },
  { key: 'occ_seller_occupies',     label: 'Seller Currently Occupies Property',       page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'occupancy' },
  { key: 'occ_not_occupied_years',  label: 'If No – How Long Since Occupied (yrs/mo)', page: 1, type: 'text',    x: 0, y: 0, width: 80,  fontSize: 10, section: 'occupancy' },

  // Section 4 – Construction Type (checkboxes)
  { key: 'const_conventional',      label: 'Construction – Conventional/Wood Frame',  page: 1, type: 'checkbox', x: 0, y: 0, section: 'construction' },
  { key: 'const_modular',           label: 'Construction – Modular',                  page: 1, type: 'checkbox', x: 0, y: 0, section: 'construction' },
  { key: 'const_manufactured',      label: 'Construction – Manufactured',             page: 1, type: 'checkbox', x: 0, y: 0, section: 'construction' },
  { key: 'const_mobile',            label: 'Construction – Mobile',                   page: 1, type: 'checkbox', x: 0, y: 0, section: 'construction' },
  { key: 'const_other',             label: 'Construction – Other (describe)',          page: 1, type: 'text',    x: 0, y: 0, width: 140, fontSize: 10, section: 'construction' },

  // Section 5 – Land
  { key: 'land_a',                  label: '5a – Fill or Expansive Soil',              page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_b',                  label: '5b – Sliding / Settling / Earth Movement', page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_c',                  label: '5c – Flood Zone / Wetlands (FEMA)',        page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_d',                  label: '5d – Drainage or Flood Problems',          page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_e',                  label: '5e – Flood Insurance Premiums Paid',       page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_f',                  label: '5f – Need for Flood Insurance',            page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_g',                  label: '5g – Boundaries Marked',                  page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_h',                  label: '5h – Stake Survey',                       page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_i',                  label: '5i – Encroachments / Boundary Disputes',  page: 1, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },

  // ── PAGE 2: LAND (cont.) / ROOF / INFESTATION / STRUCTURAL ────────────────
  { key: 'land_j',                  label: '5j – Fencing on Property',                page: 2, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_j_belongs',          label: '5j – Fencing Belongs to Property',        page: 2, type: 'choice',  x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'land' },
  { key: 'land_k',                  label: '5k – Diseased / Dead / Damaged Trees',    page: 2, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_l',                  label: '5l – Gas/Oil Wells or Lines on Property', page: 2, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_m',                  label: '5m – Oil/Gas Leases / Mineral Rights',    page: 2, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'land' },
  { key: 'land_comments',           label: 'Land – Explanation',                      page: 2, type: 'textarea', x: 0, y: 0, width: 460, height: 46, fontSize: 9, multiline: true, section: 'land' },

  // Section 6 – Roof
  { key: 'roof_age',                label: '6a – Roof Approximate Age (years)',        page: 2, type: 'text',    x: 0, y: 0, width: 45,  fontSize: 10, section: 'roof' },
  { key: 'roof_type',               label: '6a – Roof Type',                          page: 2, type: 'text',    x: 0, y: 0, width: 140, fontSize: 10, section: 'roof' },
  { key: 'roof_b',                  label: '6b – Problems with Roof / Flashing / Gutters', page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'roof' },
  { key: 'roof_b_date',             label: '6b – Date of Occurrence',                 page: 2, type: 'text',    x: 0, y: 0, width: 100, fontSize: 10, section: 'roof' },
  { key: 'roof_c',                  label: '6c – Repairs to Roof / Flashing / Gutters', page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'roof' },
  { key: 'roof_c_date_company',     label: '6c – Date and Company of Repairs',        page: 2, type: 'text',    x: 0, y: 0, width: 220, fontSize: 10, section: 'roof' },
  { key: 'roof_d',                  label: '6d – Roof Replacement',                   page: 2, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'roof' },
  { key: 'roof_d_complete',         label: '6d – Replacement: Complete',              page: 2, type: 'checkbox', x: 0, y: 0, section: 'roof' },
  { key: 'roof_d_partial',          label: '6d – Replacement: Partial',               page: 2, type: 'checkbox', x: 0, y: 0, section: 'roof' },
  { key: 'roof_layers',             label: '6e – Number of Layers',                   page: 2, type: 'text',    x: 0, y: 0, width: 35,  fontSize: 10, section: 'roof' },
  { key: 'roof_comments',           label: 'Roof – Explanation',                      page: 2, type: 'textarea', x: 0, y: 0, width: 460, height: 46, fontSize: 9, multiline: true, section: 'roof' },

  // Section 7 – Infestation
  { key: 'infest_a',                label: '7a – Termites / Wood Destroying Insects',        page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'infestation' },
  { key: 'infest_b',                label: '7b – Other Pests (rodents, bats, wildlife)',      page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'infestation' },
  { key: 'infest_c',                label: '7c – Damage by Wood Destroying Insects/Pests',   page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'infestation' },
  { key: 'infest_d',                label: '7d – Pest Control Treatment in Last 5 Years',    page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'infestation' },
  { key: 'infest_d_details',        label: '7d – Company, When, Where Treated',              page: 2, type: 'text',   x: 0, y: 0, width: 260, fontSize: 10, section: 'infestation' },
  { key: 'infest_e',                label: '7e – Current Warranty / Bait Station Coverage',  page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'infestation' },
  { key: 'infest_e_cost',           label: '7e – Annual Cost of Service Renewal ($)',        page: 2, type: 'text',   x: 0, y: 0, width: 60,  fontSize: 10, section: 'infestation' },
  { key: 'infest_e_time',           label: '7e – Time Remaining on Service Contract',        page: 2, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'infestation' },
  { key: 'infest_e_stays',          label: '7e – Treatment System Stays with Property',      page: 2, type: 'checkbox', x: 0, y: 0, section: 'infestation' },
  { key: 'infest_e_removable',      label: '7e – Treatment Subject to Removal',              page: 2, type: 'checkbox', x: 0, y: 0, section: 'infestation' },
  { key: 'infest_comments',         label: 'Infestation – Explanation',                      page: 2, type: 'textarea', x: 0, y: 0, width: 460, height: 46, fontSize: 9, multiline: true, section: 'infestation' },

  // Section 8 – Structural (starts page 2)
  { key: 'struct_a',                label: '8a – Movement / Shifting / Walls / Foundations', page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },
  { key: 'struct_b',                label: '8b – Cracks / Flaws in Walls / Ceilings / Slab', page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },
  { key: 'struct_c',                label: '8c – Corrective Action (piering / bracing)',     page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },
  { key: 'struct_d',                label: '8d – Water Leakage / Dampness',                  page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },
  { key: 'struct_e',                label: '8e – Dry Rot / Wood Rot',                        page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },
  { key: 'struct_f',                label: '8f – Problems with Windows / Exterior Doors',    page: 2, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },

  // ── PAGE 3: STRUCTURAL (cont.) / ADDITIONS / PLUMBING ─────────────────────
  { key: 'struct_g',                label: '8g – Driveways / Patios / Decks / Retaining Walls', page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },
  { key: 'struct_h',                label: '8h – Fireplace Problems (firebox / chimney)',    page: 3, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'structural' },
  { key: 'struct_h_repairs_date',   label: '8h – Date of Fireplace Repairs / Inspection',   page: 3, type: 'text',   x: 0, y: 0, width: 200, fontSize: 10, section: 'structural' },
  { key: 'struct_h_last_use',       label: '8h – Date of Last Fireplace Use',                page: 3, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'structural' },
  { key: 'struct_i',                label: '8i – Sump Pump Present',                         page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },
  { key: 'struct_i_location',       label: '8i – Sump Pump Location',                        page: 3, type: 'text',   x: 0, y: 0, width: 200, fontSize: 10, section: 'structural' },
  { key: 'struct_j',                label: '8j – Repairs / Attempts to Control Problems',    page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'structural' },
  { key: 'struct_comments',         label: 'Structural – Explanation',                       page: 3, type: 'textarea', x: 0, y: 0, width: 460, height: 46, fontSize: 9, multiline: true, section: 'structural' },

  // Section 9 – Additions & Remodeling
  { key: 'add_a',                   label: '9a – Additions / Structural Changes',             page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'additions' },
  { key: 'add_a_details',           label: '9a – Additions Details',                         page: 3, type: 'textarea', x: 0, y: 0, width: 460, height: 36, fontSize: 9, multiline: true, section: 'additions' },
  { key: 'add_b',                   label: '9b – Permits / Approvals Obtained',              page: 3, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'additions' },
  { key: 'add_b_details',           label: '9b – Explanation if No Permits',                 page: 3, type: 'textarea', x: 0, y: 0, width: 460, height: 36, fontSize: 9, multiline: true, section: 'additions' },

  // Section 10 – Plumbing
  { key: 'plumb_water_public',      label: '10a – Water Source: Public',                     page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_water_private',     label: '10a – Water Source: Private',                    page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_water_well',        label: '10a – Water Source: Well',                       page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_water_cistern',     label: '10a – Water Source: Cistern',                    page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_water_other',       label: '10a – Water Source: Other',                      page: 3, type: 'text',   x: 0, y: 0, width: 100, fontSize: 10, section: 'plumbing' },
  { key: 'plumb_well_type',         label: '10a – Well Type',                                page: 3, type: 'text',   x: 0, y: 0, width: 80,  fontSize: 10, section: 'plumbing' },
  { key: 'plumb_well_depth',        label: '10a – Well Depth',                               page: 3, type: 'text',   x: 0, y: 0, width: 40,  fontSize: 10, section: 'plumbing' },
  { key: 'plumb_well_diameter',     label: '10a – Well Diameter',                            page: 3, type: 'text',   x: 0, y: 0, width: 40,  fontSize: 10, section: 'plumbing' },
  { key: 'plumb_well_age',          label: '10a – Well Age',                                 page: 3, type: 'text',   x: 0, y: 0, width: 40,  fontSize: 10, section: 'plumbing' },
  { key: 'plumb_b',                 label: '10b – Well Water Tested for Safety',             page: 3, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'plumbing' },
  { key: 'plumb_b_date',            label: '10b – Last Water Safety Test Date',              page: 3, type: 'text',   x: 0, y: 0, width: 100, fontSize: 10, section: 'plumbing' },
  { key: 'plumb_c',                 label: '10c – Water Softener Present',                   page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'plumbing' },
  { key: 'plumb_c_leased',          label: '10c – Water Softener: Leased',                   page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_c_owned',           label: '10c – Water Softener: Owned',                    page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_d',                 label: '10d – Water Purifier System',                    page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'plumbing' },
  { key: 'plumb_d_leased',          label: '10d – Water Purifier: Leased',                   page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_d_owned',           label: '10d – Water Purifier: Owned',                    page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_sewer_public',      label: '10e – Sewage: Public Sewer',                     page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_sewer_private',     label: '10e – Sewage: Private Sewer',                    page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_sewer_septic',      label: '10e – Sewage: Septic System',                    page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_septic_tanks',      label: '10e – Number of Septic Tanks',                   page: 3, type: 'text',   x: 0, y: 0, width: 30,  fontSize: 10, section: 'plumbing' },
  { key: 'plumb_sewer_cesspool',    label: '10e – Sewage: Cesspool',                         page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_sewer_lagoon',      label: '10e – Sewage: Lagoon',                           page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_sewer_other',       label: '10e – Sewage: Other',                            page: 3, type: 'text',   x: 0, y: 0, width: 100, fontSize: 10, section: 'plumbing' },
  { key: 'plumb_f',                 label: '10f – Septic Tank / Absorption Field Location',  page: 3, type: 'text',   x: 0, y: 0, width: 300, fontSize: 10, section: 'plumbing' },
  { key: 'plumb_g',                 label: '10g – Sewer Line Clean-Out Trap Location',       page: 3, type: 'text',   x: 0, y: 0, width: 300, fontSize: 10, section: 'plumbing' },
  { key: 'plumb_h',                 label: '10h – Sewage Pump on Septic',                    page: 3, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'plumbing' },
  { key: 'plumb_i',                 label: '10i – Grinder Pump System',                      page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'plumbing' },
  { key: 'plumb_j_date',            label: '10j – Septic Last Serviced Date',                page: 3, type: 'text',   x: 0, y: 0, width: 60,  fontSize: 10, section: 'plumbing' },
  { key: 'plumb_j_by',             label: '10j – Septic Serviced By',                       page: 3, type: 'text',   x: 0, y: 0, width: 160, fontSize: 10, section: 'plumbing' },
  { key: 'plumb_k',                 label: '10k – Lawn Sprinkler System',                    page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'plumbing' },
  { key: 'plumb_k_full_yard',       label: '10k – Sprinkler Covers Full Yard',               page: 3, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'plumbing' },
  { key: 'plumb_k_last_use',        label: '10k – Sprinkler Last Use (month/year)',           page: 3, type: 'text',   x: 0, y: 0, width: 80,  fontSize: 10, section: 'plumbing' },
  { key: 'plumb_k_last_service',    label: '10k – Sprinkler Last Service (month/year)',       page: 3, type: 'text',   x: 0, y: 0, width: 80,  fontSize: 10, section: 'plumbing' },
  { key: 'plumb_l',                 label: '10l – Swimming Pool on Property',                page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'plumbing' },
  { key: 'plumb_m',                 label: '10m – Plumbing Leaks / Backups / Problems',      page: 3, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'plumbing' },
  { key: 'plumb_mat_copper',        label: '10n – Plumbing Material: Copper',                page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_mat_galvanized',    label: '10n – Plumbing Material: Galvanized',            page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_mat_pvc',           label: '10n – Plumbing Material: PVC',                   page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_mat_pex',           label: '10n – Plumbing Material: PEX',                   page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_mat_polybutylene',  label: '10n – Plumbing Material: Polybutylene',          page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_mat_unknown',       label: '10n – Plumbing Material: Unknown',               page: 3, type: 'checkbox', x: 0, y: 0, section: 'plumbing' },
  { key: 'plumb_mat_other',         label: '10n – Plumbing Material: Other',                 page: 3, type: 'text',   x: 0, y: 0, width: 100, fontSize: 10, section: 'plumbing' },
  { key: 'plumb_shutoff_location',  label: '10n – Main Water Shut-Off Location',             page: 3, type: 'text',   x: 0, y: 0, width: 200, fontSize: 10, section: 'plumbing' },
  { key: 'plumb_o',                 label: '10o – Back Flow Prevention Device',               page: 3, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'plumbing' },
  { key: 'plumb_comments',          label: 'Plumbing – Explanation',                         page: 3, type: 'textarea', x: 0, y: 0, width: 460, height: 36, fontSize: 9, multiline: true, section: 'plumbing' },

  // ── PAGE 4: HVAC / ELECTRICAL / HAZARDOUS ─────────────────────────────────

  // Section 11 – HVAC
  { key: 'hvac_a',                  label: '11a – Has Air Conditioning',                     page: 4, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'hvac' },
  { key: 'hvac_a_central_elec',     label: '11a – AC: Central Electric',                     page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_a_central_gas',      label: '11a – AC: Central Gas',                          page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_a_heat_pump',        label: '11a – AC: Heat Pump',                            page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_a_window',           label: '11a – AC: Window Unit(s)',                        page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_a_unit1',            label: '11a – AC Unit 1 Details',                        page: 4, type: 'text',   x: 0, y: 0, width: 380, fontSize: 9, section: 'hvac' },
  { key: 'hvac_a_unit2',            label: '11a – AC Unit 2 Details',                        page: 4, type: 'text',   x: 0, y: 0, width: 380, fontSize: 9, section: 'hvac' },
  { key: 'hvac_a_using',            label: '11a – Currently Using AC',                       page: 4, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'hvac' },
  { key: 'hvac_a_last_use',         label: '11a – AC Last Use Date',                         page: 4, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'hvac' },
  { key: 'hvac_b',                  label: '11b – Has Heating System',                       page: 4, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'hvac' },
  { key: 'hvac_b_electric',         label: '11b – Heat: Electric',                           page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_b_fuel_oil',         label: '11b – Heat: Fuel Oil',                           page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_b_natural_gas',      label: '11b – Heat: Natural Gas',                        page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_b_heat_pump',        label: '11b – Heat: Heat Pump',                          page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_b_propane',          label: '11b – Heat: Propane',                            page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_b_fuel_tank',        label: '11b – Heat: Fuel Tank',                          page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_b_other',            label: '11b – Heat: Other',                              page: 4, type: 'text',   x: 0, y: 0, width: 80, fontSize: 10, section: 'hvac' },
  { key: 'hvac_b_unit1',            label: '11b – Heat Unit 1 Details',                      page: 4, type: 'text',   x: 0, y: 0, width: 380, fontSize: 9, section: 'hvac' },
  { key: 'hvac_b_unit2',            label: '11b – Heat Unit 2 Details',                      page: 4, type: 'text',   x: 0, y: 0, width: 380, fontSize: 9, section: 'hvac' },
  { key: 'hvac_b_using',            label: '11b – Currently Using Heating',                  page: 4, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'hvac' },
  { key: 'hvac_b_last_use',         label: '11b – Heating Last Use Date',                    page: 4, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'hvac' },
  { key: 'hvac_c',                  label: '11c – Rooms Without Heat or AC',                 page: 4, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'hvac' },
  { key: 'hvac_c_rooms',            label: '11c – Which Rooms',                              page: 4, type: 'text',   x: 0, y: 0, width: 260, fontSize: 10, section: 'hvac' },
  { key: 'hvac_d',                  label: '11d – Has Water Heater',                         page: 4, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'hvac' },
  { key: 'hvac_d_electric',         label: '11d – Water Heater: Electric',                   page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_d_gas',              label: '11d – Water Heater: Gas',                        page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_d_solar',            label: '11d – Water Heater: Solar',                      page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_d_tankless',         label: '11d – Water Heater: Tankless',                   page: 4, type: 'checkbox', x: 0, y: 0, section: 'hvac' },
  { key: 'hvac_d_unit1',            label: '11d – Water Heater Unit 1 Details',              page: 4, type: 'text',   x: 0, y: 0, width: 380, fontSize: 9, section: 'hvac' },
  { key: 'hvac_d_unit2',            label: '11d – Water Heater Unit 2 Details',              page: 4, type: 'text',   x: 0, y: 0, width: 380, fontSize: 9, section: 'hvac' },
  { key: 'hvac_e',                  label: '11e – HVAC Problems',                            page: 4, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'hvac' },
  { key: 'hvac_e_details',          label: '11e – HVAC Problem Details',                     page: 4, type: 'textarea', x: 0, y: 0, width: 460, height: 36, fontSize: 9, multiline: true, section: 'hvac' },

  // Section 12 – Electrical
  { key: 'elec_mat_copper',         label: '12a – Electrical Material: Copper',               page: 4, type: 'checkbox', x: 0, y: 0, section: 'electrical' },
  { key: 'elec_mat_aluminum',       label: '12a – Electrical Material: Aluminum',             page: 4, type: 'checkbox', x: 0, y: 0, section: 'electrical' },
  { key: 'elec_mat_unknown',        label: '12a – Electrical Material: Unknown',              page: 4, type: 'checkbox', x: 0, y: 0, section: 'electrical' },
  { key: 'elec_panel_breaker',      label: '12b – Panel Type: Breaker',                       page: 4, type: 'checkbox', x: 0, y: 0, section: 'electrical' },
  { key: 'elec_panel_fuse',         label: '12b – Panel Type: Fuse',                          page: 4, type: 'checkbox', x: 0, y: 0, section: 'electrical' },
  { key: 'elec_panel_location',     label: '12b – Panel Location',                            page: 4, type: 'text',   x: 0, y: 0, width: 240, fontSize: 10, section: 'electrical' },
  { key: 'elec_panel_amps',         label: '12b – Panel Size (amps)',                         page: 4, type: 'text',   x: 0, y: 0, width: 140, fontSize: 10, section: 'electrical' },
  { key: 'elec_c',                  label: '12c – Electrical System Problems',                page: 4, type: 'choice',  x: 0, y: 0, choices: ['yes', 'no'], section: 'electrical' },
  { key: 'elec_c_details',          label: '12c – Electrical Problem Details',                page: 4, type: 'textarea', x: 0, y: 0, width: 460, height: 36, fontSize: 9, multiline: true, section: 'electrical' },

  // Section 13 – Hazardous
  { key: 'haz_a',                   label: '13a – Underground Tanks',                        page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_b',                   label: '13b – Landfill on Property',                     page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_c',                   label: '13c – Toxic Substances (tires, batteries, etc.)', page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_d',                   label: '13d – Radioactive / Hazardous Contamination',    page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_e',                   label: '13e – Testing for Hazardous Items',              page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_f',                   label: '13f – Professional Radon Testing',               page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_g',                   label: '13g – Radon Mitigation System',                  page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_h',                   label: '13h – Mold Testing / Mitigation',                page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_i',                   label: '13i – Other Environmental Issues',               page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_j',                   label: '13j – Controlled Substances Manufactured',       page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_k',                   label: '13k – Methamphetamine Manufactured',             page: 4, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'hazardous' },
  { key: 'haz_comments',            label: 'Hazardous – Explanation',                        page: 4, type: 'textarea', x: 0, y: 0, width: 460, height: 46, fontSize: 9, multiline: true, section: 'hazardous' },

  // ── PAGE 5: TAXES / HOA / INSPECTIONS / OTHER MATTERS ────────────────────

  // Section 14 – Taxes & HOA
  { key: 'tax_a_outside_city',      label: '14a – Outside City Limits',                      page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_a_bonds',             label: '14a – Current/Pending Bonds or Special Taxes',   page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_a_bonds_amount',      label: '14a – Bond/Special Tax Amount ($)',              page: 5, type: 'text',   x: 0, y: 0, width: 80,  fontSize: 10, section: 'taxes_hoa' },
  { key: 'tax_b',                   label: '14b – Tax Credits or Tax Freeze',                page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_c',                   label: '14c – Tax Abatement',                            page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_d',                   label: '14d – Neighborhood Condition / Proposed Change', page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_e',                   label: '14e – Common Elements / Area Defect',            page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_f',                   label: '14f – Change in Assessments or Fees',            page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_g',                   label: '14g – Privately Owned Streets',                  page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_h',                   label: '14h – Historic / Conservation / Special District', page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_i',                   label: '14i – Right of First Refusal',                   page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_i_days',              label: '14i – Days Required for Notice',                 page: 5, type: 'text',   x: 0, y: 0, width: 40,  fontSize: 10, section: 'taxes_hoa' },
  { key: 'tax_j',                   label: '14j – HOA / Subdivision Restrictions',           page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_k',                   label: '14k – Violations of Covenants',                  page: 5, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_l',                   label: '14l – HOA Transfer / Initiation Fee',            page: 5, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_l_amount',            label: '14l – HOA Fee Amount ($)',                       page: 5, type: 'text',   x: 0, y: 0, width: 80,  fontSize: 10, section: 'taxes_hoa' },
  { key: 'tax_m',                   label: '14m – Subject to HOA Fee',                       page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_m_paid_until',        label: '14m – HOA Dues Paid Until',                      page: 5, type: 'text',   x: 0, y: 0, width: 100, fontSize: 10, section: 'taxes_hoa' },
  { key: 'tax_m_amount',            label: '14m – HOA Dues Amount ($)',                      page: 5, type: 'text',   x: 0, y: 0, width: 60,  fontSize: 10, section: 'taxes_hoa' },
  { key: 'tax_m_freq_yearly',       label: '14m – HOA Frequency: Yearly',                    page: 5, type: 'checkbox', x: 0, y: 0, section: 'taxes_hoa' },
  { key: 'tax_m_freq_semi',         label: '14m – HOA Frequency: Semi-Annually',             page: 5, type: 'checkbox', x: 0, y: 0, section: 'taxes_hoa' },
  { key: 'tax_m_freq_monthly',      label: '14m – HOA Frequency: Monthly',                   page: 5, type: 'checkbox', x: 0, y: 0, section: 'taxes_hoa' },
  { key: 'tax_m_freq_quarterly',    label: '14m – HOA Frequency: Quarterly',                 page: 5, type: 'checkbox', x: 0, y: 0, section: 'taxes_hoa' },
  { key: 'tax_m_sent_to',           label: '14m – HOA Dues Sent To',                         page: 5, type: 'text',   x: 0, y: 0, width: 360, fontSize: 10, section: 'taxes_hoa' },
  { key: 'tax_m_includes',          label: '14m – HOA Dues Include',                         page: 5, type: 'text',   x: 0, y: 0, width: 460, fontSize: 10, section: 'taxes_hoa' },
  { key: 'tax_m_contact',           label: '14m – HOA Contact Name / Phone / Website',       page: 5, type: 'textarea', x: 0, y: 0, width: 460, height: 36, fontSize: 9, multiline: true, section: 'taxes_hoa' },
  { key: 'tax_n',                   label: '14n – Secondary Master HOA Fee',                 page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'taxes_hoa' },
  { key: 'tax_comments',            label: 'Taxes/HOA – Explanation',                        page: 5, type: 'textarea', x: 0, y: 0, width: 460, height: 36, fontSize: 9, multiline: true, section: 'taxes_hoa' },

  // Section 15 – Previous Inspections
  { key: 'inspect_last_12mo',       label: '15 – Inspected in Last 12 Months',               page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'inspections' },

  // Section 16 – Other Matters
  { key: 'other_a',                 label: '16a – Party Walls / Easements / Common Areas',   page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_b',                 label: '16b – Fire Damage',                              page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_c',                 label: '16c – Liens (other than mortgage)',               page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_d',                 label: '16d – Violations of Laws or Regulations',        page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_e',                 label: '16e – Other Conditions Affecting Value',          page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_f',                 label: '16f – Conditions Preventing Sale Completion',    page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_g',                 label: '16g – Animals / Pets in Property',               page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_h',                 label: '16h – General or Pet Stains on Carpet/Flooring', page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_i',                 label: '16i – Missing Keys for Exterior Doors',          page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_i_locks',           label: '16i – List Locks Without Keys',                  page: 5, type: 'text',   x: 0, y: 0, width: 260, fontSize: 10, section: 'other_matters' },
  { key: 'other_j',                 label: '16j – Zoning / Setback / Restriction Violations', page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_k',                 label: '16k – Unrecorded Interests',                     page: 5, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },

  // ── PAGE 6: OTHER MATTERS (cont.) / UTILITIES / ELECTRONICS ──────────────
  { key: 'other_l',                 label: '16l – Clear Title Interference',                 page: 6, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_m',                 label: '16m – Existing / Threatened Legal Action',       page: 6, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_n',                 label: '16n – Litigation or Settlement',                 page: 6, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_o',                 label: '16o – Added Insulation Since Ownership',         page: 6, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_p',                 label: '16p – Replaced Appliances in Last 5 Years',     page: 6, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_q',                 label: '16q – Transferable Warranties',                  page: 6, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_r',                 label: '16r – Insurance Claims in Last 5 Years',         page: 6, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_r_repairs',         label: '16r – Repairs from Claims Completed',           page: 6, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'other_matters' },
  { key: 'other_s',                 label: '16s – Synthetic Stucco (EIFS)',                  page: 6, type: 'choice', x: 0, y: 0, choices: ['yes', 'no'], section: 'other_matters' },
  { key: 'other_comments',          label: 'Other Matters – Explanation',                    page: 6, type: 'textarea', x: 0, y: 0, width: 460, height: 46, fontSize: 9, multiline: true, section: 'other_matters' },

  // Section 17 – Utilities
  { key: 'util_electric_name',      label: '17 – Electric Company Name',                     page: 6, type: 'text',   x: 0, y: 0, width: 180, fontSize: 10, section: 'utilities' },
  { key: 'util_electric_phone',     label: '17 – Electric Company Phone',                    page: 6, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'utilities' },
  { key: 'util_gas_name',           label: '17 – Gas Company Name',                          page: 6, type: 'text',   x: 0, y: 0, width: 180, fontSize: 10, section: 'utilities' },
  { key: 'util_gas_phone',          label: '17 – Gas Company Phone',                         page: 6, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'utilities' },
  { key: 'util_water_name',         label: '17 – Water Company Name',                        page: 6, type: 'text',   x: 0, y: 0, width: 180, fontSize: 10, section: 'utilities' },
  { key: 'util_water_phone',        label: '17 – Water Company Phone',                       page: 6, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'utilities' },
  { key: 'util_trash_name',         label: '17 – Trash Company Name',                        page: 6, type: 'text',   x: 0, y: 0, width: 180, fontSize: 10, section: 'utilities' },
  { key: 'util_trash_phone',        label: '17 – Trash Company Phone',                       page: 6, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'utilities' },
  { key: 'util_other1_name',        label: '17 – Other Utility 1 Name',                      page: 6, type: 'text',   x: 0, y: 0, width: 180, fontSize: 10, section: 'utilities' },
  { key: 'util_other1_phone',       label: '17 – Other Utility 1 Phone',                     page: 6, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'utilities' },
  { key: 'util_other2_name',        label: '17 – Other Utility 2 Name',                      page: 6, type: 'text',   x: 0, y: 0, width: 180, fontSize: 10, section: 'utilities' },
  { key: 'util_other2_phone',       label: '17 – Other Utility 2 Phone',                     page: 6, type: 'text',   x: 0, y: 0, width: 120, fontSize: 10, section: 'utilities' },

  // Section 18 – Electronic Systems
  { key: 'elec_sys_present',        label: '18 – Electronic Systems Staying with Property',  page: 6, type: 'choice', x: 0, y: 0, choices: ['na', 'yes', 'no'], section: 'electronics' },
  { key: 'elec_sys_list',           label: '18 – List of Electronic Systems',                page: 6, type: 'textarea', x: 0, y: 0, width: 460, height: 46, fontSize: 9, multiline: true, section: 'electronics' },

  // ── PAGE 7: FIXTURES ───────────────────────────────────────────────────────
  { key: 'fix_ac_window',           label: 'AC Window Unit(s)',                               page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_ac_window_count',     label: 'AC Window Units – Count',                        page: 7, type: 'text',   x: 0, y: 0, width: 25, fontSize: 9, section: 'fixtures' },
  { key: 'fix_ac_central',          label: 'AC Central System',                              page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_attic_fan',           label: 'Attic Fan',                                      page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_boat_dock',           label: 'Boat Dock',                                      page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_boat_dock_id',        label: 'Boat Dock – ID #',                               page: 7, type: 'text',   x: 0, y: 0, width: 60, fontSize: 9, section: 'fixtures' },
  { key: 'fix_ceiling_fans',        label: 'Ceiling Fan(s)',                                 page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_ceiling_fans_count',  label: 'Ceiling Fans – Count',                          page: 7, type: 'text',   x: 0, y: 0, width: 25, fontSize: 9, section: 'fixtures' },
  { key: 'fix_central_vac',         label: 'Central Vac and Attachments',                    page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_closet_systems',      label: 'Closet Systems',                                 page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_closet_location',     label: 'Closet Systems – Location',                      page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_camera_surveillance', label: 'Camera / Surveillance Equipment',                page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_doorbell',            label: 'Doorbell',                                       page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_video_doorbell',      label: 'Video Doorbell',                                 page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_elec_air_cleaner',    label: 'Electric Air Cleaner / Purifier',                page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_ev_charging',         label: 'Electric Car Charging Equipment',                page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_exhaust_fans_baths',  label: 'Exhaust Fan(s) – Baths',                        page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fences_invisible',    label: 'Fences – Invisible & Controls',                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fireplace_count',     label: 'Fireplace(s) – Count',                          page: 7, type: 'text',   x: 0, y: 0, width: 25, fontSize: 9, section: 'fixtures' },
  { key: 'fix_fp1_location',        label: 'Fireplace 1 – Location',                         page: 7, type: 'text',   x: 0, y: 0, width: 60, fontSize: 9, section: 'fixtures' },
  { key: 'fix_fp2_location',        label: 'Fireplace 2 – Location',                         page: 7, type: 'text',   x: 0, y: 0, width: 60, fontSize: 9, section: 'fixtures' },
  { key: 'fix_fp1_chimney',         label: 'Fireplace 1 – Chimney',                          page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp2_chimney',         label: 'Fireplace 2 – Chimney',                          page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp1_gas_logs',        label: 'Fireplace 1 – Gas Logs',                         page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp2_gas_logs',        label: 'Fireplace 2 – Gas Logs',                         page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp1_gas_starter',     label: 'Fireplace 1 – Gas Starter',                      page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp2_gas_starter',     label: 'Fireplace 2 – Gas Starter',                      page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp1_heat_recirc',     label: 'Fireplace 1 – Heat Re-circulator',               page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp2_heat_recirc',     label: 'Fireplace 2 – Heat Re-circulator',               page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp1_insert',          label: 'Fireplace 1 – Insert',                           page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp2_insert',          label: 'Fireplace 2 – Insert',                           page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp1_wood_burning',    label: 'Fireplace 1 – Wood Burning',                     page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp2_wood_burning',    label: 'Fireplace 2 – Wood Burning',                     page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fp1_other',           label: 'Fireplace 1 – Other',                            page: 7, type: 'text',   x: 0, y: 0, width: 60, fontSize: 9, section: 'fixtures' },
  { key: 'fix_fp2_other',           label: 'Fireplace 2 – Other',                            page: 7, type: 'text',   x: 0, y: 0, width: 60, fontSize: 9, section: 'fixtures' },
  { key: 'fix_fountain',            label: 'Fountain(s)',                                    page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_furnace',             label: 'Furnace / Heat Pump / Other Heating System',     page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_garage_keyless',      label: 'Garage Door Keyless Entry',                      page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_garage_opener',       label: 'Garage Door Opener Unit(s)',                     page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_garage_opener_count', label: 'Garage Door Openers – Count',                   page: 7, type: 'text',   x: 0, y: 0, width: 25, fontSize: 9, section: 'fixtures' },
  { key: 'fix_garage_remote',       label: 'Garage Door Remote(s)',                          page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_garage_remote_count', label: 'Garage Door Remotes – Count',                   page: 7, type: 'text',   x: 0, y: 0, width: 25, fontSize: 9, section: 'fixtures' },
  { key: 'fix_generator',           label: 'Generator',                                      page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_humidifier',          label: 'Humidifier',                                     page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_intercom',            label: 'Intercom',                                       page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_jetted_tub',          label: 'Jetted Tub',                                     page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  // Kitchen appliances
  { key: 'fix_stove_range',         label: 'Kitchen – Stove / Range',                        page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_stove_elec',          label: 'Stove – Electric',                               page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_stove_gas',           label: 'Stove – Gas',                                    page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_stove_convection',    label: 'Stove – Convection',                             page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_builtin_oven',        label: 'Kitchen – Built-in Oven',                        page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_oven_elec',           label: 'Oven – Electric',                                page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_oven_gas',            label: 'Oven – Gas',                                     page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_oven_convection',     label: 'Oven – Convection',                              page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_cooktop',             label: 'Kitchen – Cooktop',                              page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_cooktop_elec',        label: 'Cooktop – Electric',                             page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_cooktop_gas',         label: 'Cooktop – Gas',                                  page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_range_hood',          label: 'Kitchen – Range Exhaust Hood',                   page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_microwave',           label: 'Kitchen – Microwave Oven',                       page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_dishwasher',          label: 'Kitchen – Dishwasher',                           page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_disposal',            label: 'Kitchen – Disposal',                             page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_freezer',             label: 'Kitchen – Freezer',                              page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_freezer_location',    label: 'Freezer – Location',                             page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_fridge1',             label: 'Refrigerator #1',                                page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fridge1_location',    label: 'Refrigerator #1 – Location',                     page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_fridge2',             label: 'Refrigerator #2',                                page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_fridge2_location',    label: 'Refrigerator #2 – Location',                     page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_trash_compactor',     label: 'Kitchen – Trash Compactor',                      page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_washer',              label: 'Laundry – Washer',                               page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_dryer',               label: 'Laundry – Dryer',                                page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_dryer_elec',          label: 'Dryer – Electric',                               page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_dryer_gas',           label: 'Dryer – Gas',                                    page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  // Mounted entertainment
  { key: 'fix_tv1',                 label: 'Mounted TV #1',                                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_tv1_location',        label: 'TV #1 – Location',                               page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_tv2',                 label: 'Mounted TV #2',                                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_tv2_location',        label: 'TV #2 – Location',                               page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_tv3',                 label: 'Mounted TV #3',                                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_tv3_location',        label: 'TV #3 – Location',                               page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_tv4',                 label: 'Mounted TV #4',                                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_tv4_location',        label: 'TV #4 – Location',                               page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_speakers1',           label: 'Mounted Speakers #1',                            page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_speakers1_location',  label: 'Speakers #1 – Location',                         page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_speakers2',           label: 'Mounted Speakers #2',                            page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_speakers2_location',  label: 'Speakers #2 – Location',                         page: 7, type: 'text',   x: 0, y: 0, width: 80, fontSize: 9, section: 'fixtures' },
  { key: 'fix_entertain_other1',    label: 'Mounted Entertainment Other #1',                 page: 7, type: 'text',   x: 0, y: 0, width: 120, fontSize: 9, section: 'fixtures' },
  { key: 'fix_entertain_other2',    label: 'Mounted Entertainment Other #2',                 page: 7, type: 'text',   x: 0, y: 0, width: 120, fontSize: 9, section: 'fixtures' },
  { key: 'fix_entertain_other3',    label: 'Mounted Entertainment Other #3',                 page: 7, type: 'text',   x: 0, y: 0, width: 120, fontSize: 9, section: 'fixtures' },
  { key: 'fix_entertain_other4',    label: 'Mounted Entertainment Other #4',                 page: 7, type: 'text',   x: 0, y: 0, width: 120, fontSize: 9, section: 'fixtures' },
  // Other fixtures
  { key: 'fix_outside_cooking',     label: 'Outside Cooking Unit',                           page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_propane_tank',        label: 'Propane Tank',                                   page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_propane_owned',       label: 'Propane Tank – Owned',                           page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_propane_leased',      label: 'Propane Tank – Leased',                          page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_security',            label: 'Security System',                                page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_security_owned',      label: 'Security System – Owned',                        page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_security_leased',     label: 'Security System – Leased',                       page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_smoke_detectors',     label: 'Smoke / Fire Detector(s)',                       page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_smoke_count',         label: 'Smoke Detectors – Count',                        page: 7, type: 'text',   x: 0, y: 0, width: 25, fontSize: 9, section: 'fixtures' },
  { key: 'fix_sheds',               label: 'Shed(s)',                                        page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_sheds_count',         label: 'Sheds – Count',                                  page: 7, type: 'text',   x: 0, y: 0, width: 25, fontSize: 9, section: 'fixtures' },
  { key: 'fix_spa_hot_tub',         label: 'Spa / Hot Tub',                                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_spa_sauna',           label: 'Spa / Sauna',                                    page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_spa_equipment',       label: 'Spa Equipment',                                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_sprinkler_timer',     label: 'Sprinkler System – Auto Timer',                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_sprinkler_backflow',  label: 'Sprinkler System – Back Flow Valve',             page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_sprinkler_controls',  label: 'Sprinkler System – Components & Controls',       page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_statuary',            label: 'Statuary / Yard Art',                            page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_swing_set',           label: 'Swing Set / Playset',                            page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_sump_pumps',          label: 'Sump Pump(s)',                                   page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_sump_count',          label: 'Sump Pumps – Count',                             page: 7, type: 'text',   x: 0, y: 0, width: 25, fontSize: 9, section: 'fixtures' },
  { key: 'fix_pool',                label: 'Swimming Pool',                                  page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_pool_heater',         label: 'Swimming Pool Heater',                           page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_pool_equipment',      label: 'Swimming Pool Equipment',                        page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_tv_antenna',          label: 'TV Antenna / Receiver / Satellite Dish',          page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_tv_antenna_owned',    label: 'TV Antenna – Owned',                             page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_tv_antenna_leased',   label: 'TV Antenna – Leased',                            page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_water_heater',        label: 'Water Heater(s)',                                page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_water_softener',      label: 'Water Softener',                                 page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_water_purification',  label: 'Water Purification System',                      page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_water_pur_owned',     label: 'Water Purification – Owned',                     page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_water_pur_leased',    label: 'Water Purification – Leased',                    page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_wood_stove',          label: 'Wood Burning Stove',                             page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_yard_light',          label: 'Yard Light',                                     page: 7, type: 'fixture_status', x: 0, y: 0, choices: ['OS','EX','NA','NS'], section: 'fixtures' },
  { key: 'fix_yard_light_elec',     label: 'Yard Light – Electric',                          page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_yard_light_gas',      label: 'Yard Light – Gas',                               page: 7, type: 'checkbox', x: 0, y: 0, section: 'fixtures' },
  { key: 'fix_other1',              label: 'Fixtures – Other 1',                             page: 7, type: 'text',   x: 0, y: 0, width: 160, fontSize: 9, section: 'fixtures' },
  { key: 'fix_other2',              label: 'Fixtures – Other 2',                             page: 7, type: 'text',   x: 0, y: 0, width: 160, fontSize: 9, section: 'fixtures' },
  { key: 'fix_other3',              label: 'Fixtures – Other 3',                             page: 7, type: 'text',   x: 0, y: 0, width: 160, fontSize: 9, section: 'fixtures' },
  { key: 'fix_other4',              label: 'Fixtures – Other 4',                             page: 7, type: 'text',   x: 0, y: 0, width: 160, fontSize: 9, section: 'fixtures' },
  { key: 'fix_other5',              label: 'Fixtures – Other 5',                             page: 7, type: 'text',   x: 0, y: 0, width: 160, fontSize: 9, section: 'fixtures' },
  { key: 'fix_other6',              label: 'Fixtures – Other 6',                             page: 7, type: 'text',   x: 0, y: 0, width: 160, fontSize: 9, section: 'fixtures' },

  // ── PAGE 8: ADDITIONAL DISCLOSURE & SIGNATURES ────────────────────────────
  { key: 'additional_disclosures',  label: 'Additional Material Information Disclosure',      page: 8, type: 'textarea', x: 0, y: 0, width: 470, height: 58, fontSize: 9, multiline: true, section: 'final' },
  { key: 'seller_1_signature',      label: 'Seller 1 – Signature',                           page: 8, type: 'signature', x: 0, y: 0, width: 200, section: 'signatures' },
  { key: 'seller_1_date',           label: 'Seller 1 – Date',                                page: 8, type: 'date',   x: 0, y: 0, width: 100, fontSize: 10, section: 'signatures' },
  { key: 'seller_2_signature',      label: 'Seller 2 – Signature',                           page: 8, type: 'signature', x: 0, y: 0, width: 200, section: 'signatures' },
  { key: 'seller_2_date',           label: 'Seller 2 – Date',                                page: 8, type: 'date',   x: 0, y: 0, width: 100, fontSize: 10, section: 'signatures' },
  { key: 'buyer_1_signature',       label: 'Buyer 1 – Signature',                            page: 8, type: 'signature', x: 0, y: 0, width: 200, section: 'signatures' },
  { key: 'buyer_1_date',            label: 'Buyer 1 – Date',                                 page: 8, type: 'date',   x: 0, y: 0, width: 100, fontSize: 10, section: 'signatures' },
  { key: 'buyer_2_signature',       label: 'Buyer 2 – Signature',                            page: 8, type: 'signature', x: 0, y: 0, width: 200, section: 'signatures' },
  { key: 'buyer_2_date',            label: 'Buyer 2 – Date',                                 page: 8, type: 'date',   x: 0, y: 0, width: 100, fontSize: 10, section: 'signatures' },
]

// Helper: get fields for a specific page
export const getFieldsByPage = (page: number) =>
  SELLER_DISCLOSURE_FIELDS.filter(f => f.page === page)

// Helper: get fields by section
export const getFieldsBySection = (section: string) =>
  SELLER_DISCLOSURE_FIELDS.filter(f => f.section === section)

// Section metadata for UI display
export const SECTION_META: Record<string, { title: string; icon: string; page: number }> = {
  header:        { title: 'Seller & Property',            icon: '🏠', page: 1 },
  occupancy:     { title: 'Occupancy',                    icon: '👤', page: 1 },
  construction:  { title: 'Construction Type',            icon: '🏗️', page: 1 },
  land:          { title: 'Land, Soils & Boundaries',     icon: '🌍', page: 1 },
  roof:          { title: 'Roof',                         icon: '🏚️', page: 2 },
  infestation:   { title: 'Infestation',                  icon: '🐛', page: 2 },
  structural:    { title: 'Structural & Basement',        icon: '🧱', page: 2 },
  additions:     { title: 'Additions & Remodeling',       icon: '🔨', page: 3 },
  plumbing:      { title: 'Plumbing',                     icon: '🚿', page: 3 },
  hvac:          { title: 'Heating & Air Conditioning',   icon: '🌡️', page: 4 },
  electrical:    { title: 'Electrical System',            icon: '⚡', page: 4 },
  hazardous:     { title: 'Hazardous Conditions',         icon: '☢️', page: 4 },
  taxes_hoa:     { title: 'Taxes, Neighborhood & HOA',   icon: '🏛️', page: 5 },
  inspections:   { title: 'Previous Inspections',         icon: '🔍', page: 5 },
  other_matters: { title: 'Other Matters',                icon: '📋', page: 5 },
  utilities:     { title: 'Utilities',                    icon: '💡', page: 6 },
  electronics:   { title: 'Electronic Systems',           icon: '📡', page: 6 },
  fixtures:      { title: 'Fixtures & Appliances',        icon: '🛋️', page: 7 },
  final:         { title: 'Additional Disclosures',       icon: '📝', page: 8 },
  signatures:    { title: 'Signatures',                   icon: '✍️', page: 8 },
}
